using System;using System.IO;using System.Linq;using System.Collections.Generic;using Autodesk.AutoCAD.Runtime;using Autodesk.AutoCAD.DatabaseServices;using Autodesk.AutoCAD.Geometry;using BHT.Bridge;using BHT.Core;using AcApp=Autodesk.AutoCAD.ApplicationServices.Core.Application;
public class Sign0613Probe{
static List<string> log=new List<string>();static void Check(string name,bool ok){log.Add((ok?"PASS ":"FAIL ")+name);}
static IEnumerable<Entity> Entities(Transaction tr,Database db,string name){var bt=(BlockTable)tr.GetObject(db.BlockTableId,OpenMode.ForRead);return ((BlockTableRecord)tr.GetObject(bt[name],OpenMode.ForRead)).Cast<ObjectId>().Select(id=>(Entity)tr.GetObject(id,OpenMode.ForRead));}
static List<string> Texts(Transaction tr,Database db,string name){var result=new List<string>();foreach(var e in Entities(tr,db,name)){var t=e as DBText;if(t!=null)result.Add(t.TextString);var b=e as BlockReference;if(b!=null){result.AddRange(Texts(tr,db,((BlockTableRecord)tr.GetObject(b.BlockTableRecord,OpenMode.ForRead)).Name));foreach(ObjectId id in b.AttributeCollection){var a=tr.GetObject(id,OpenMode.ForRead) as AttributeReference;if(a!=null)result.Add(a.TextString);}}}return result;}
[CommandMethod("BHTSIGN0613PROBE")]public static void Run(){log.Clear();var doc=AcApp.DocumentManager.MdiActiveDocument;var db=doc.Database;try{
Check("Bridge-version-0.6.13",typeof(TdtSignLibrary).Assembly.GetName().Version.ToString()=="0.6.53.0");Check("Core-version-0.6.13",typeof(SignPresentation).Assembly.GetName().Version.ToString()=="0.6.53.0");
var codes=new[]{"W.225","S.501@500","P.106c","R.404d","I.401","I.402","IE.473","R.E,9b@07:30-19:15","R.E,10b@22:00-05:30"};var names=new List<string>();
foreach(var c in codes){var r=TdtSignLibrary.EnsureBlock(db,c);Check(c+"-import",r.Ok);if(!r.Ok){log.Add("DETAIL "+r.Error);continue;}names.Add(r.BlockName);
using(var tr=db.TransactionManager.StartTransaction()){
var es=Entities(tr,db,r.BlockName).ToList();
if(c=="I.401"){Check("I401-white-filled-field",es.OfType<Hatch>().Any(h=>h.Color.Red==255&&h.Color.Green==255&&h.Color.Blue==255));Check("I401-black-borders",es.OfType<Hatch>().Count(h=>h.Color.Red==0&&h.Color.Green==0&&h.Color.Blue==0)>=2);}
if(c=="IE.473")Check("IE473-native-text",Texts(tr,db,r.BlockName).Contains("GIẢM TỐC ĐỘ")&&Texts(tr,db,r.BlockName).Contains("SLOW DOWN"));
if(SignPresentation.HasZoneTime(c)){Check(c+"-white-background",es.OfType<BlockReference>().Any(b=>Entities(tr,db,((BlockTableRecord)tr.GetObject(b.BlockTableRecord,OpenMode.ForRead)).Name).OfType<Hatch>().Any(h=>h.Color.Red==255&&h.Color.Green==255&&h.Color.Blue==255))); var text=Texts(tr,db,r.BlockName);Check(c+"-hours",text.Contains(SignPresentation.ZoneTime(c).Replace("-"," - ")));log.Add("TEXT "+c+" "+string.Join("|",text));}
if(c=="P.106c"||c=="R.404d")foreach(var face in es.OfType<BlockReference>()){var b=(BlockTableRecord)tr.GetObject(face.BlockTableRecord,OpenMode.ForRead);var order=((DrawOrderTable)tr.GetObject(b.DrawOrderTableId,OpenMode.ForRead)).GetFullDrawOrder(0).Cast<ObjectId>().ToList();var fills=order.Select(id=>tr.GetObject(id,OpenMode.ForRead)).OfType<Hatch>().ToList();var red=fills.Where(h=>(h.ColorIndex==1 || (h.Color.Red>200&&h.Color.Green<80&&h.Color.Blue<80))).ToList();var other=fills.Where(h=>h.ColorIndex==30||h.ColorIndex==150||h.ColorIndex==7||h.ColorIndex==255).ToList();Check(c+"-red-overlay",red.Count>0&&other.All(h=>order.IndexOf(h.ObjectId)<red.Max(x=>order.IndexOf(x.ObjectId))));}
tr.Commit();}}
var main=TdtSignLibrary.EnsureBlock(db,"W.225");var plate=TdtSignLibrary.EnsureBlock(db,"S.501@500");string assembly=SignAssembly.Ensure(db,new[]{main.BlockName,plate.BlockName});names.Insert(0,assembly);
using(var tr=db.TransactionManager.StartTransaction()){
var faces=Entities(tr,db,assembly).OfType<BlockReference>().OrderBy(b=>b.GeometricExtents.MinPoint.Y).ToList();var lower=faces[0].GeometricExtents;var upper=faces[1].GeometricExtents;double w=lower.MaxPoint.X-lower.MinPoint.X;Check("supplement-width-not-larger-than-main",w<=upper.MaxPoint.X-upper.MinPoint.X);Check("plates-gap-0.20",Math.Abs(upper.MinPoint.Y-lower.MaxPoint.Y-.2)<1e-6);log.Add("SIZE supplemental="+w+" main="+(upper.MaxPoint.X-upper.MinPoint.X));
var bt=(BlockTable)tr.GetObject(db.BlockTableId,OpenMode.ForRead);var ms=(BlockTableRecord)tr.GetObject(bt[BlockTableRecord.ModelSpace],OpenMode.ForWrite);int i=0;foreach(var n in names){var b=new BlockReference(new Point3d(100000+(i%5)*8,100000+(i/5)*7,0),bt[n]);ms.AppendEntity(b);tr.AddNewlyCreatedDBObject(b,true);var text=new DBText{TextString=i==0?"W225+S501 500m":codes[i-1],Height=.3,Position=b.Position+new Vector3d(-2,-.6,0)};ms.AppendEntity(text);tr.AddNewlyCreatedDBObject(text,true);i++;}tr.Commit();}
}catch(System.Exception ex){log.Add("FAIL exception "+ex);}File.WriteAllLines(Environment.GetEnvironmentVariable("BHT_0613_REPORT") ?? @"C:\Users\Le Bao\BHT_TEST_0613\native-live.txt",log);foreach(var s in log)doc.Editor.WriteMessage("\n"+s);}
}
