(vl-load-com)
(setq *sign-test-fail* 0)
(defun signs-check (name ok) (if (not ok) (setq *sign-test-fail* (1+ *sign-test-fail*))) (princ (strcat "\n" (if ok "PASS " "FAIL ") "SIGN " name)))
(setq pl (entmakex '((0 . "LWPOLYLINE") (100 . "AcDbEntity") (8 . "0") (100 . "AcDbPolyline") (90 . 2) (70 . 0) (10 0.0 0.0) (10 100.0 0.0))))
(bht:route-create "SIGNROUTE" pl "TIM_DUONG" 20.0 0.0 nil "test")
(bht:route-set-start-dir "SIGNROUTE" '(0.0 0.0 0.0) 1)
(setq rec (list (cons "nhom" "BIEN_BAO") (cons "route_id" "SIGNROUTE") (cons "phia_tuyen" "PHAI")))
(setq result (bht:kh-auto-transform rec '(50.0 -5.0 0.0) 1.0))
(signs-check "right-forward-90" (equal (cadr result) (/ pi 2.0) 1e-8))
(setq rec (bht:set rec "phia_tuyen" "TRAI"))
(signs-check "left-forward-minus90" (equal (cadr (bht:kh-auto-transform rec '(50.0 5.0 0.0) 1.0)) (- (/ pi 2.0)) 1e-8))
(bht:route-set-start-dir "SIGNROUTE" '(100.0 0.0 0.0) -1)
(setq result (bht:kh-auto-transform rec '(50.0 -5.0 0.0) 1.0))
(signs-check "reverse-left" (equal (sin (cadr result)) 1.0 1e-8))
(setq rec (bht:set rec "nhom" "COC_TIEU"))
(setq result (bht:kh-auto-transform rec '(50.0 -5.0 0.0) 1.0))
(signs-check "post-stays-at-survey" (equal (car result) '(50.0 -5.0 0.0) 1e-8))
(signs-check "post-rotates" (equal (abs (sin (cadr result))) 1.0 1e-8))
(setq rec (bht:set rec "route_id" ""))
(signs-check "no-route-zero" (equal (cadr (bht:kh-auto-transform rec '(50.0 -5.0 0.0) 1.0)) 0.0 1e-8))
(bht:block "SIGN_CUSTOM_TEST" (list (bht:line-g '(0.0 0.0 0.0) '(1.0 1.0 0.0))))
(setq rec (bht:set rec "custom_block" "SIGN_CUSTOM_TEST"))
(signs-check "object-custom-priority" (= (bht:kh-block rec) "SIGN_CUSTOM_TEST"))
(setq rec (list (cons "nhom" "BIEN_BAO") (cons "ma_hieu" "P.127") (cons "mo_ta" "gioihan80")))
(signs-check "description-import-80" (= (bht:kh-block rec) "BHT_TDT_V51_P_127_80"))
(signs-check "nonuniform-global-custom-factor-ignored" (progn (bht:meta-set "kh_block_bien_bao" "SIGN_CUSTOM_TEST") (bht:meta-set "kh_block_factor_bien_bao" "3") (setq rec (bht:set rec "custom_block" "SIGN_CUSTOM_TEST")) (equal (bht:kh-scale-for rec) (bht:kh-scale) 1e-8)))
(bht:meta-set "kh_block_bien_bao" "")
(bht:meta-set "kh_block_factor_bien_bao" "1")
(setq survey (entmakex '((0 . "POINT") (10 50.0 -5.0 0.0))))
(bht:pt-write-xdata survey "SIGN-PT" "SIGN" "1" "Sign" -5.0 50.0 0.0 "BIEN_BAO" "test" "gioihan80" "")
(setq fields (list (cons "nhom" "BIEN_BAO") (cons "ma_hieu" "P.127") (cons "mo_ta" "gioihan80") (cons "custom_block" "SIGN_CUSTOM_TEST")))
(setq new (bht:obj-create "OBJ-SIGN" fields '("SIGN-PT") nil))
(signs-check "lisp-create-custom" (and (car new) (= (bht:get (bht:obj-read "OBJ-SIGN") "custom_block") "SIGN_CUSTOM_TEST")))
(setq rec (bht:obj-read "OBJ-SIGN"))
(setq rec (bht:set (bht:set (bht:set rec "custom_block" "") "route_id" "SIGNROUTE") "phia_tuyen" "TRAI"))
(bht:obj-write "OBJ-SIGN" rec)
(setq sync1 (bht:symbol-sync '("OBJ-SIGN")))
(setq sym (cadr (assoc "OBJ-SIGN" (bht:group-pairs (bht:tagged-pairs "INSERT" "BHT_KH" 1)))))
(signs-check "sync-creates-speed80" (and sym (= (cdr (assoc 2 (entget sym))) "BHT_TDT_V51_P_127_80")))
(setq before (entget sym) sync2 (bht:symbol-sync '("OBJ-SIGN")))
(signs-check "repeat-sync-idempotent" (and (= (cdr (assoc 'created sync2)) 0) (equal before (entget sym))))
(entmod (bht:dxf-put (entget sym) 50 0.321))
(bht:symbol-sync '("OBJ-SIGN"))
(signs-check "manual-rotation-preserved" (equal (cdr (assoc 50 (entget sym))) 0.321 1e-8))
;; Free placement persists independently from route, and leads via picked corners.
(setq source-record (bht:obj-read "OBJ-SIGN") source-point (entget survey))
(bht:kh-free-apply "OBJ-SIGN" '(65.0 -25.0 0.0) 0.75 '((55.0 -8.0 0.0) (60.0 -18.0 0.0)))
(setq free-record (bht:obj-read "OBJ-SIGN") free-leader (cadr (assoc "OBJ-SIGN" (bht:group-pairs (bht:tagged-pairs "LWPOLYLINE" "BHT_KH" 1)))))
(signs-check "free-position-angle" (and (equal (cdr (assoc 10 (entget sym))) '(65.0 -25.0 0.0) 1e-8) (equal (cdr (assoc 50 (entget sym))) 0.75 1e-8)))
(signs-check "free-route-and-RTK-kept" (and (= (bht:get source-record "route_id") (bht:get free-record "route_id")) (equal source-point (entget survey))))
(signs-check "free-polyline-four-vertices" (and free-leader (= (cdr (assoc 90 (entget free-leader))) 4)
  (equal (mapcar 'cdr (vl-remove-if-not '(lambda (pair) (= (car pair) 10)) (entget free-leader))) '((50.0 -5.0) (55.0 -8.0) (60.0 -18.0) (65.0 -25.0)) 1e-8)))
(setq free-before (entget free-leader) ins-before (entget sym))
(bht:symbol-sync '("OBJ-SIGN"))
(signs-check "free-repeat-idempotent" (and (equal free-before (entget free-leader)) (equal ins-before (entget sym))))
(entmod (bht:dxf-put (entget sym) 10 '(70.0 -30.0 0.0)))
(bht:symbol-sync '("OBJ-SIGN"))
(signs-check "free-move-updates-end-keeps-corners" (equal (mapcar 'cdr (vl-remove-if-not '(lambda (pair) (= (car pair) 10)) (entget free-leader))) '((50.0 -5.0) (55.0 -8.0) (60.0 -18.0) (70.0 -30.0)) 1e-8))
(bht:kh-free-apply "OBJ-SIGN" '(80.0 -20.0 0.0) 1.25 nil)
(signs-check "free-replace-route-straight" (and (= (length (bht:tagged-pairs "LWPOLYLINE" "BHT_KH" 1)) 0) (= (length (bht:tagged-pairs "LINE" "BHT_KH" 1)) 1)
  (equal (cdr (assoc 10 (entget sym))) '(80.0 -20.0 0.0) 1e-8)))
(bht:kh-free-apply "OBJ-SIGN" '(65.0 -25.0 0.0) 0.75 '((60.0 -18.0 0.0)))
(bht:symbol-reset '("OBJ-SIGN"))
(signs-check "free-reset-to-route" (and (= (bht:get (bht:obj-read "OBJ-SIGN") "kh_mode") "")
 (= (length (bht:tagged-pairs "LWPOLYLINE" "BHT_KH" 1)) 0)
 (equal (cdr (assoc 10 (entget sym))) (car (bht:kh-route-transform (bht:obj-read "OBJ-SIGN") '(50.0 -5.0 0.0) (bht:kh-scale))) 1e-8)))
(setq before-missing-ids (bht:obj-ids) before-missing-sym (entget sym))
(signs-check "missing-free-object-returns-error" (eq (car (bht:kh-place-free "__MISSING__")) 'LOI))
(signs-check "missing-free-object-API-error" (= (car (bht:api-sign-free "__MISSING__")) "LOI"))
(signs-check "empty-free-object-returns-error" (eq (car (bht:kh-place-free nil)) 'LOI))
(signs-check "missing-object-does-not-write" (and (equal before-missing-ids (bht:obj-ids)) (equal before-missing-sym (entget sym))))
(bht:kh-free-apply "OBJ-SIGN" '(65.0 -25.0 0.0) 0.75 '((55.0 -8.0 0.0) (60.0 -18.0 0.0)))
(setq leader-order (cadr (assoc "OBJ-SIGN" (bht:group-pairs (bht:tagged-pairs "LWPOLYLINE" "BHT_KH" 1)))))
(bht:kh-free-apply "OBJ-SIGN" '(65.0 -25.0 0.0) 0.75 '((60.0 -18.0 0.0) (55.0 -8.0 0.0)))
(signs-check "changed-waypoint-order-kept" (equal (bht:kh-leader-xy (bht:kh-via-points (bht:obj-read "OBJ-SIGN"))) '((60.0 -18.0) (55.0 -8.0))))
(signs-check "changed-waypoint-order-on-entity" (equal (mapcar 'cdr (vl-remove-if-not '(lambda (pair) (= (car pair) 10)) (entget leader-order))) '((50.0 -5.0) (60.0 -18.0) (55.0 -8.0) (65.0 -25.0)) 1e-8))
(setq leader-before (entget leader-order))
(bht:symbol-sync '("OBJ-SIGN"))
(signs-check "reordered-leader-repeat-idempotent" (equal leader-before (entget leader-order)))
(bht:obj-write "OBJ-NOPOINT" '(("nhom" . "BIEN_BAO")))
(signs-check "free-no-RTK-returns-error" (eq (car (bht:kh-place-free "OBJ-NOPOINT")) 'LOI))
(bht:obj-delete "OBJ-NOPOINT")
(bht:symbol-reset '("OBJ-SIGN"))
(princ (strcat "\nSIGN-TEST-FAIL=" (itoa *sign-test-fail*)))
(princ)
