;;; BHT 0.4.2 - phien S0: nap, phien ban, BHTTEST, DCL tinh
(load "C:/Users/Le Bao/BHT_TEST_V042/t_common.lsp")
(tbegin "S0")
(setq e (tload))
(tchk "T00" "nạp BHT-0.4.2 (đường dẫn có dấu); *bht-version* = 0.4.2" (and (null e) (= *bht-version* "0.4.2")) (if e e (strcat *bht-version* " / " *bht-build*)))
(tchk "T01" "thông báo APPLOAD đúng nguyên văn" (= (bht:load-message) "BHT 0.4.2 đã nạp thành công.") (bht:load-message))
(setq r (tsafe "T02" "BHTTEST" '(lambda () (bht:selftest))))
(if r (tchk "T02" "BHTTEST tự kiểm tra hàm (0 FAIL, >= 45)" (and (= (cadr r) 0) (>= (car r) 45)) (strcat (itoa (car r)) " pass, " (itoa (cadr r)) " fail")))
(setq bad nil keys nil)
(foreach b *bht-ui-buttons*
  (if (and (/= (caddr b) "BHTUIREFRESH") (not (eval (read (strcat "C:" (caddr b)))))) (setq bad (cons (caddr b) bad)))
  (if (member (car b) keys) (setq bad (cons (strcat "trùng khóa " (car b)) bad)) (setq keys (cons (car b) keys))))
(setq tpl (bht:ui-dcl-template) opn 0 cls 0 unk nil)
(foreach l tpl
  (setq opn (+ opn (length (vl-remove-if-not '(lambda (c) (= c 123)) (vl-string->list l))))
        cls (+ cls (length (vl-remove-if-not '(lambda (c) (= c 125)) (vl-string->list l))))))
(foreach b *bht-ui-buttons* (if (not (vl-some '(lambda (l) (vl-string-search (strcat "key = \"" (car b) "\"") l)) tpl)) (setq unk (cons (car b) unk))))
(setq path (bht:ui-write-dcl) left nil)
(if path (progn (setq f (open path "r"))
                (while (setq l (read-line f)) (if (wcmatch l "*`@*`@*") (setq left (cons l left))))
                (close f) (vl-file-delete path)))
(tchk "T03" "DCL tĩnh: mọi nút gọi lệnh có thật, khóa duy nhất, nút nào cũng có trong mẫu, không sót @nhãn@, { } cân bằng (42 nút)"
      (and (null bad) (null unk) (= opn cls) path (null left) (= (length *bht-ui-buttons*) 42))
      (strcat "nút=" (itoa (length *bht-ui-buttons*)) " lỗi=" (vl-princ-to-string bad) " thiếu=" (vl-princ-to-string unk)
              " {=" (itoa opn) " }=" (itoa cls) " sót=" (vl-princ-to-string left)))
(setq cmds '(c:BHTSAPNHAN c:BHTNHANTUDONG c:BHTTHUTUVE c:BHTVEMODEL c:BHTKYHIEU c:BHTDOITUONG c:BHTCHENANH))
(tchk "T04" "lệnh 0.3.3 vẫn được định nghĩa trong 0.4.2" (vl-every '(lambda (c) (eval c)) cmds) nil)
(setq r (vl-catch-all-apply 'bht:ui-validate nil))
(if (and (not (vl-catch-all-error-p r)) r)
  (tchk "T05" "load_dialog DCL trong Core Console" T nil)
  (tskip "T05" "mở bảng DCL BHT (load_dialog / new_dialog / start_dialog)" "BLOCKED" "Core Console không có DCL - kiểm tra thủ công theo CHECKLIST"))
(setq bad nil)
(foreach c '(c:BHTTEST c:BHTKT c:BHTTRANGTHAI c:BHTHELP)
  (if (vl-catch-all-error-p (vl-catch-all-apply c nil)) (setq bad (cons c bad))))
(tchk "T06" "chạy lệnh không tương tác trên bản vẽ trống: BHTTEST, BHTKT, BHTTRANGTHAI, BHTHELP" (null bad) bad)
;; --- API cho plugin .NET, Lisp khong phu thuoc palette ---
(tchk "T07" "13 hàm bht:api-* đăng ký vl-acad-defun (gọi được từ .NET Application.Invoke)" (= *bht-api-registered* 13) *bht-api-registered*)
(setq r (bht:api-version))
(tchk "T08" "bht:api-version = (OK 0.4.2 1 build)" (equal r (list "OK" "0.4.2" "1" *bht-build*)) r)
(setq r (bht:api-info-object "KHONG-CO"))
(tchk "T09" "API không hỏi người dùng, trả về danh sách chuỗi; hồ sơ không có -> dòng '(không có hồ sơ)'" (and (= (car r) "OK") (vl-every '(lambda (x) (= (type x) 'STR)) r)) r)
(setq r (bht:api-photo-path "KHONG-CO"))
(tchk "T10" "API báo LỖI rõ ràng (không ném lỗi): ảnh không có" (and (= (car r) "LOI") (= (type (cadr r)) 'STR)) r)
(setq r (bht:api-check))
(tchk "T11" "bht:api-check trên bản vẽ trống: OK + số lỗi/cảnh báo" (and (= (car r) "OK") (wcmatch (cadr r) "loi=*") (wcmatch (caddr r) "canh_bao=*")) (list (cadr r) (caddr r)))
(tchk "T12" "không còn c:BHT/c:BTH trong Lisp; DCL dự phòng là c:BHTDCL; có lệnh nạp lại c:BHTLOAD"
      (and (not (eval 'c:BHT)) (not (eval 'c:BTH)) c:BHTDCL c:BHTLOAD) nil)
(setq r (vl-catch-all-apply 'c:BHTLOAD nil))
(tchk "T13" "BHTLOAD khi DLL không nằm cạnh Lisp: báo rõ, không lỗi" (not (vl-catch-all-error-p r)) nil)
(setq r (bht:api-point-style "1"))
(tchk "T14" "POINT mặc định là dấu X đúng tâm, kích thước tuyệt đối 1 unit; API sắp nhãn chạy được"
      (and (= (car r) "OK") (= (getvar "PDMODE") 3) (equal (getvar "PDSIZE") 1.0 1e-9)) r)
(setq r (vl-catch-all-apply 'bht:block-load-dwg
                            (list (strcat *T-DIR* "run/route_src.dwg") "KHAC")))
(tchk "T15" "nạp DWG ngoài thành block tùy chọn, giữ hệ số đổi đơn vị, không để INSERT tạm"
      (and (not (vl-catch-all-error-p r)) r (tblsearch "BLOCK" r) (> *bht-block-load-factor* 0.0)
           (null (ssget "_X" (list '(0 . "INSERT") (cons 2 r)))))
      (if (vl-catch-all-error-p r) (vl-catch-all-error-message r) (list r *bht-block-load-factor*)))
(tend "S0")
(princ)
